server:
  port: 8082

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/course?createDatabaseIfNotExist=true&allowPublicKeyRetrieve=true&sslMode=DISABLED
  jmx:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

jwt:
  config:
    type: signed
